#ifndef PHYSICAL_CONSTANTS
#define PHYSICAL_CONSTANTS

#define ACC_GRAVITY -9.81  // m s^-2
#define DENSITY_SEAWATER  1025  // kg m^-3
#define KINEMATIC_VISCOSITY_SEAWATER 0.0000015 // m^2 s^-1

#endif // PHYSICAL_CONSTANTS
